#!/bin/bash

# Clean up previously running apps, gracefully at first then harshly
killall -TERM matchbox-window-manager 2>/dev/null;
sleep 2;
killall -9 matchbox-window-manager 2>/dev/null;

# Disable DPMS / Screen blanking
xset -dpms
xset s off

# Reset the framebuffer's colour-depth
#fbset -depth $( cat /sys/module/*fb*/parameters/fbdepth );

# Start the window manager (remove "-use_cursor no" if you actually want mouse interaction)
matchbox-window-manager -use_titlebar no -use_cursor no &

# Show splash
feh -F ~/magic_lamp/Server/assets/splash.png & feh_pid=$!
sleep 1

# Compile client
cd ~/magic_lamp/Client
grunt

# Start server
cd ~/magic_lamp/Server/src
nice python -u main.py > ~/log/server.log 2>&1 &

# Start the browser
cd ~/kiosk-browser
./browser http://localhost:9002 1> console.log 2> error.log & browser_pid=$!

sleep 5
kill -9 $feh_pid

wait $browser_pid

